//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaCalculator.AreaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AreaServiceReference.AreaCalculatorWebServiceSoap")]
    public interface AreaCalculatorWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AreaCalculator.AreaServiceReference.HelloWorldResponse HelloWorld(AreaCalculator.AreaServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaCalculator.AreaServiceReference.HelloWorldResponse> HelloWorldAsync(AreaCalculator.AreaServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AreaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Area", ReplyAction="*")]
        AreaCalculator.AreaServiceReference.AreaResponse Area(AreaCalculator.AreaServiceReference.AreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Area", ReplyAction="*")]
        System.Threading.Tasks.Task<AreaCalculator.AreaServiceReference.AreaResponse> AreaAsync(AreaCalculator.AreaServiceReference.AreaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AreaCalculator.AreaServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AreaCalculator.AreaServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaCalculator.AreaServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AreaCalculator.AreaServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Area", Namespace="http://tempuri.org/", Order=0)]
        public AreaCalculator.AreaServiceReference.AreaRequestBody Body;
        
        public AreaRequest() {
        }
        
        public AreaRequest(AreaCalculator.AreaServiceReference.AreaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AreaRequestBody {
        
        public AreaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AreaCalculator.AreaServiceReference.AreaResponseBody Body;
        
        public AreaResponse() {
        }
        
        public AreaResponse(AreaCalculator.AreaServiceReference.AreaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AreaResult;
        
        public AreaResponseBody() {
        }
        
        public AreaResponseBody(string AreaResult) {
            this.AreaResult = AreaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreaCalculatorWebServiceSoapChannel : AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreaCalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap>, AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap {
        
        public AreaCalculatorWebServiceSoapClient() {
        }
        
        public AreaCalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreaCalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaCalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaCalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaCalculator.AreaServiceReference.HelloWorldResponse AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap.HelloWorld(AreaCalculator.AreaServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AreaCalculator.AreaServiceReference.HelloWorldRequest inValue = new AreaCalculator.AreaServiceReference.HelloWorldRequest();
            inValue.Body = new AreaCalculator.AreaServiceReference.HelloWorldRequestBody();
            AreaCalculator.AreaServiceReference.HelloWorldResponse retVal = ((AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaCalculator.AreaServiceReference.HelloWorldResponse> AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap.HelloWorldAsync(AreaCalculator.AreaServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaCalculator.AreaServiceReference.HelloWorldResponse> HelloWorldAsync() {
            AreaCalculator.AreaServiceReference.HelloWorldRequest inValue = new AreaCalculator.AreaServiceReference.HelloWorldRequest();
            inValue.Body = new AreaCalculator.AreaServiceReference.HelloWorldRequestBody();
            return ((AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AreaCalculator.AreaServiceReference.AreaResponse AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap.Area(AreaCalculator.AreaServiceReference.AreaRequest request) {
            return base.Channel.Area(request);
        }
        
        public string Area() {
            AreaCalculator.AreaServiceReference.AreaRequest inValue = new AreaCalculator.AreaServiceReference.AreaRequest();
            inValue.Body = new AreaCalculator.AreaServiceReference.AreaRequestBody();
            AreaCalculator.AreaServiceReference.AreaResponse retVal = ((AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap)(this)).Area(inValue);
            return retVal.Body.AreaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AreaCalculator.AreaServiceReference.AreaResponse> AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap.AreaAsync(AreaCalculator.AreaServiceReference.AreaRequest request) {
            return base.Channel.AreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AreaCalculator.AreaServiceReference.AreaResponse> AreaAsync() {
            AreaCalculator.AreaServiceReference.AreaRequest inValue = new AreaCalculator.AreaServiceReference.AreaRequest();
            inValue.Body = new AreaCalculator.AreaServiceReference.AreaRequestBody();
            return ((AreaCalculator.AreaServiceReference.AreaCalculatorWebServiceSoap)(this)).AreaAsync(inValue);
        }
    }
}
